bosunAddress: "bosun.example.com"
applications:
  zookeeper:
    services:
      client:
        maxFailures: 2
        interval: 60s
        type: tcp_connect
        instances:
          "zookeeper1.example.com:2181": False
          "zookeeper2.example.com:2181": False
          "zookeeper3.example.com:2181": False
          "zookeeper4.example.com:2181": False
          "zookeeper5.example.com:2181": False
  hdfs:
    services:
      journalnode:
        maxFailures: 2
        interval: 60s
        type: http_status
        instances:
          "http://hdfs-journalnode1.example.com:8480": False
          "http://hdfs-journalnode2.example.com:8480": False
          "http://hdfs-journalnode3.example.com:8480": False
          "http://hdfs-journalnode4.example.com:8480": False
          "http://hdfs-journalnode5.example.com:8480": False
      namenode:
        maxFailures: 1
        interval: 60s
        type: http_status
        instances:
          "http://hdfs-namenode1.example.com:50070": False
          "http://hdfs-namenode2.example.com:50070": False
      datanode:
        maxFailures: 2
        interval: 60s
        type: http_status
        instances:
          "http://hdfs-datanode1.example.com:50075": False
          "http://hdfs-datanode2.example.com:50075": False
          "http://hdfs-datanode3.example.com:50075": False
          "http://hdfs-datanode4.example.com:50075": False
          "http://hdfs-datanode5.example.com:50075": False
